"datasource_id","error","name","value"
"t_08e096b6ec1844839972faba67d5301e","Connection lost","source","snowflake"
"t_08e096b6ec1844839972faba67d5301e","Data corruption","source","snowflake"
"t_08e096b6ec1844839972faba67d5301e","Internal server error","source","bigquery"
"t_08e096b6ec1844839972faba67d5301e","Query timeout","source","bigquery"
