"error"
"Connection Timeout. If this connector is scheduled it will be retried automatically"
"The specified bucket does not exist"
